version: 0.2
phases:
  install:
    runtime-versions:
       docker: 18
  build:
    commands:
      - bash ./aws-cli-v2.sh
      - bash ./pip3-twine.sh
      - echo "AWS CLI and Twine Installed"
      - bash ./install-python-packages.sh <AWSACCOUNTID>
